name: Likeaboss
main: cam.Likeaboss
version: 1.4.1
author: bm01

commands:
  lab:
    description: Likeaboss base command
    permission: lab
    usage: /lab [info | reload | clear | viewer | ignore | list | spawn]

permissions:
  lab.*:
    description: Gives access to all /lab permissions
    children:
      lab.info: true
      lab.reload: true
      lab.clear: true
      lab.viewer: true
      lab.ignore.*: true
      lab.list: true
      lab.spawn: true
    default: op
  lab:
    description: Likeaboss base command
    default: true
  lab.info:
    description: Gives some game info
    default: false
  lab.reload:
    description: Reloads config
    default: false
  lab.clear:
    description: Clears /lab.info data
    default: false
  lab.viewer:
    description: Displays bosses health
    default: false
  lab.ignore.*:
    description: Gives access to all /lab ignore permissions
    children:
      lab.ignore: true
      lab.ignore.immediate: true
    default: false
  lab.ignore:
    description: Toggle ignore bosses, only work is there is no boss near the player
    default: false
  lab.ignore.immediate:
    description: Allow to use /lab ignore even near a boss
    default: false
  lab.list:
    description: Displays bosses location
    default: false
  lab.spawn:
    description: Spawns a boss
    default: false