name: Likeaboss
main: cam.Likeaboss
version: 1.2.1
author: bm01

commands:
  lab:
    description: Likeaboss base command
    permission: lab
    usage: /lab [info | reload | clear | viewer | list | spawn]

permissions:
  lab.*:
    description: Gives access to all Lab commands
    children:
      lab.info: true
      lab.reload: true
      lab.clear: true
      lab.viewer: true
      lab.list: true
      lab.spawn: true
    default: op
  lab:
    description: Likeaboss base command
    default: true
  lab.info:
    description: Give some game info
    default: false
  lab.reload:
    description: Reload config
    default: false
  lab.clear:
    description: Clear /lab.info data
    default: false
  lab.viewer:
    description: Display bosses health
    default: false
  lab.list:
    description: Display bosses location
    default: false
  lab.spawn:
    description: Spawn a boss
    default: false