diamond:
  Helmet:
    diamond_Helmet_diamond_helmet:
      Enabled: true
      Probability: 50
      DropProbability: 50
  Chestplate:
    diamond_Chestplate_diamond_chestplate:
      Enabled: true
      Probability: 100
      DropProbability: 50
  Leggings:
    diamond_Leggings_diamond_leggings:
      Enabled: true
      Probability: 100
      DropProbability: 50
  Boots:
    diamond_Boots_diamond_boots:
      Enabled: true
      Probability: 50
      DropProbability: 50
  Weapon:
    diamond_Weapon_diamond_sword:
      Enabled: true
      Probability: 100
      DropProbability: 50
ConfigVersion: '${project.version}'
