Blaze:
  EntityType: Blaze
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      Blaze_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
CaveSpider:
  EntityType: CaveSpider
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      CaveSpider_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 3.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Creeper:
  EntityType: Creeper
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      Creeper_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 3.75
    Damage: 2.0
    Experience: 10.5
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Enderman:
  EntityType: Enderman
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      Enderman_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 3.75
    Damage: 2.0
    Experience: 10.5
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Ghast:
  EntityType: Ghast
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  ReturnToSenderImmune: true
  Loot:
    FirstRoll:
      Ghast_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 4
        MaxQuantity: 8
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
LavaSlime:
  EntityType: LavaSlime
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      LavaSlime_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 3
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
PigZombie:
  EntityType: PigZombie
  Aggressive: true
  Baby: false
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      PigZombie_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 1
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Silverfish:
  EntityType: SilverFish
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      Silverfish_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 7.5
    Damage: 4.0
    Experience: 5.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Skeleton:
  EntityType: Skeleton
  WitherSkeleton: false
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      Skeleton_FirstRoll_FirstItem:
        Probability: 3.5
        MinQuantity: 1
        MaxQuantity: 1
      Skeleton_FirstRoll_SecondItem:
        Probability: 20.0
        MinQuantity: 2
        MaxQuantity: 4
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Slime:
  EntityType: Slime
  MinimumSize: 2
  MaximumSize: 4
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      Slime_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 3
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Spider:
  EntityType: Spider
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      Spider_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 3.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Witch:
  EntityType: Witch
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      Witch_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 3
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Wither:
  EntityType: WitherBoss
  HealthRegenPerSecond: 2
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Spawn:
    Probability: 25.0
    SpawnerProbability: 0.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256
  Stats:
    Health: 5.0
    Damage: 1.0
    Experience: 180.0
  Loot:
    netherstar:
      Wither_netherstar_netherstar:
        Probability: 100.0
        MinQuantity: 1
        MaxQuantity: 1
    diamonds:
      Wither_diamonds_diamond:
        Probability: 100.0
        MinQuantity: 20
        MaxQuantity: 30
  Immunity:
    BlockExplosion: true
    EntityExplosion: true
    Fire: false
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Magic: true
Zombie:
  EntityType: Zombie
  EquipmentSet: diamond
  Baby: false
  Villager: false
  mcMMOXPBonus: 0
  HeroesKillingExperience: 0.0
  Loot:
    FirstRoll:
      Zombie_FirstRoll_FirstItem:
        Probability: 20.0
        MinQuantity: 1
        MaxQuantity: 3
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MinSpawnHeight: 0.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
ConfigVersion: '2.4'
