Command:
  Ignore:
    Delay: 120
  Spawn:
    Max: 50
Message:
  PlayerFoundBoss:
    ToPlayer: '&cYou attacked a Corrupted {BOSSNAME}!'
    ToOthers: '&c{PLAYER} found a Corrupted {BOSSNAME}!'
  BossFoundPlayer:
    ToPlayer: '&cA Corrupted {BOSSNAME} found you!'
    ToOthers: '&cA Corrupted {BOSSNAME} found {PLAYER}!'
  Proximity: '&4You sense a magical disruption...'
  
  CustomBossName: 'Corrupted {BOSSNAME} &7[{HEALTH}/{MAXHEALTH}]'
  ViewerMessage: 'Corrupted {BOSSNAME} Health: &7{HEALTH} (-{DAMAGE})'
  ViewerDefeated: 'Corrupted {BOSSNAME} has been defeated.'
  ViewerDamageAbsorbed: "Corrupted {BOSSNAME}'s armour absorbed the damage."
Task:
  DrawBossEffect: 1.0
  CheckEntityProximity: 0.5
  CheckEntityExistence: 2.0
  SavePlayerData: 150.0
  LoadPlayerData: 5.0
Boss:
  OverwriteDrops: false
  SetHealthAsMultiplier: true
  SetDamageAsMultiplier: true
  SetExperienceAsMultiplier: true
  EnableBiomes: false

CheckUpdateOnStartup: true
ReloadAfterUpdating: true
LogLevel: INFO

#Do not touch this variable
ConfigVersion: '2.3.2'