# If this is set to true, the other parts of the config file will be ignored
enable-all-spells: true
# If true, use a whitelist, if false, use a blacklist
use-whitelist: true
whitelist:
    - spell1
    - spell2
    - etc
blacklist:

#Do not touch this variable
ConfigVersion: '2.3.1'