Boss: {}
Ability: {}
Loot:
  FirstRoll:
    world_FirstRoll_FirstItem:
      Probability: 10.0
      MinQuantity: 1
      MaxQuantity: 2
    world_FirstRoll_SecondItem:
      Probability: 15.0
      MinQuantity: 1
      MaxQuantity: 2
    world_FirstRoll_ThirdItem:
      Probability: 20.0
      MinQuantity: 1
      MaxQuantity: 3
    world_FirstRoll_FourthItem:
      Probability: 25.0
      MinQuantity: 1
      MaxQuantity: 3
  SecondRoll:
    world_SecondRoll_FirstItem:
      Probability: 17.5
      MinQuantity: 1
      MaxQuantity: 2
    world_SecondRoll_SecondItem:
      Probability: 17.5
      MinQuantity: 1
      MaxQuantity: 2
    world_SecondRoll_ThirdItem:
      Probability: 17.5
      MinQuantity: 1
      MaxQuantity: 2
    world_SecondRoll_FourthItem:
      Probability: 1.0
      MinQuantity: 1
      MaxQuantity: 1
  ThirdRoll:
    world_ThirdRoll_FirstItem:
      Probability: 3.0
      MinQuantity: 1
      MaxQuantity: 3
    world_ThirdRoll_SecondItem:
      Probability: 3.0
      MinQuantity: 1
      MaxQuantity: 2
    world_ThirdRoll_ThirdItem:
      Probability: 3.0
      MinQuantity: 1
      MaxQuantity: 1
ConfigVersion: '2.4'
