AP25:
  Type: ArmorPierce
  Probability: 100.0
  Value: 25.0
FP2:
  Type: FirePunch
  Probability: 100.0
  Ticks: 2
KB2:
  Type: Knockback
  Probability: 100.0
  VerticalCoef: 2.0
  HorizontalCoef: 3.0
MN4:
  Type: Minions
  Probability: 100.0
  Cooldown: 7.5
  EntityType: Silverfish
  Amount: 3
  Range: 2
SL2:
  Type: Slow
  Probability: 100.0
  Amplifier: 2
  Duration: 3.0