Command:
  Ignore:
    Delay: 120
Message:
  PlayerFoundBoss:
    ToPlayer: '&cOh noes, that''s a boss!'
    ToOthers: '&c{PLAYER} found a boss&c!'
  BossFoundPlayer:
    ToPlayer: '&cSneaky boss.'
    ToOthers: '&cA boss found {PLAYER}!'
  TooFar: '&cYou''re too far away.'
  Proximity: '&4You feel an evil presence...'
Task:
  VisualEffect: 1.0
  CheckBossProximity: 0.5
  CheckEntityHealth: 2.0
  CheckEntityExistence: 5.0