Boss:
  Blaze:
    Spawn: 3.0 1.0 128
    Stats: 5.5 2.5 8.0
    Drop:
      FirstRoll:
        FirstItem: 370:0 20.0 1 1
  CaveSpider:
    Spawn: 3.0 1.0 128
    Stats: 5.5 2.75 8.0
    Drop:
      FirstRoll:
        FirstItem: 376:0 20.0 1 2
  Creeper:
    Spawn: 3.0 1.0 128
    Stats: 3.75 2.5 10.5
    Drop:
      FirstRoll:
        FirstItem: 46:0 20.0 1 2
  Enderman:
    Spawn: 3.0 1.0 128
    Stats: 3.75 2.5 10.5
    Drop:
      FirstRoll:
        FirstItem: 121:0 20.0 1 2
  Ghast:
    Spawn: 3.0 1.0 128
    Stats: 5.5 2.5 8.0
    Drop:
      FirstRoll:
        FirstItem: 348:0 20.0 4 8
  LavaSlime:
    Spawn: 3.0 1.0 128
    Stats: 5.5 2.5 8.0
    Drop:
      FirstRoll:
        FirstItem: 341:0 20.0 1 3
  PigZombie:
    Spawn: 3.0 1.0 128
    Stats: 5.5 2.5 8.0
    Drop:
      FirstRoll:
        FirstItem: 266:0 20.0 1 1
  Silverfish:
    Spawn: 3.0 1.0 128
    Stats: 7.5 7.5 5.0
    Drop:
      FirstRoll:
        FirstItem: 350:0 20.0 1 2
  Skeleton:
    Spawn: 3.0 1.0 128
    Stats: 5.5 2.5 8.0
    Drop:
      FirstRoll:
        FirstItem: 261:0 3.5 1 1
        SecondItem: 262:0 20.0 2 4
  Slime:
    Spawn: 3.0 1.0 128
    Stats: 5.5 2.5 8.0
    Drop:
      FirstRoll:
        FirstItem: 378:0 20.0 1 3
  Spider:
    Spawn: 3.0 1.0 128
    Stats: 5.5 2.75 8.0
    Drop:
      FirstRoll:
        FirstItem: 35:0 20.0 1 2
  Zombie:
    Spawn: 3.0 1.0 128
    Stats: 5.5 2.5 8.0
    Drop:
      FirstRoll:
        FirstItem: 288:0 20.0 1 3
Drop:
  FirstRoll:
    FirstItem: 264:0 10.0 1 2
    SecondItem: 266:0 15.0 1 2
    ThirdItem: 265:0 20.0 1 3
    FourthItem: 263:0 25.0 1 3
  SecondRoll:
    FirstItem: 364:0 17.5 1 2
    SecondItem: 320:0 17.5 1 2
    ThirdItem: 366:0 17.5 1 2
    FourthItem: 354:0 1.0 1 1
  ThirdRoll:
    FirstItem: 280:0 3.0 1 3
    SecondItem: 374:0 3.0 1 2
    ThirdItem: 281:0 3.0 1 1
