AP25:
  Type: ArmorPierce
  Message: "&4{BOSSNAME} Boss used Armor Pierce."
  ActivationChance: 10.0
  AssignationChance: 100.0
  MinimumRange: 0
  MaximumRange: 16
  Value: 25.0
FP2:
  Type: FirePunch
  Message: "&4{BOSSNAME} Boss used Fire Punch."
  ActivationChance: 15.0
  AssignationChance: 100.0
  MinimumRange: 0
  MaximumRange: 16
  Ticks: 2
KB2:
  Type: Knockback
  Message: "&4{BOSSNAME} Boss used Knockback."
  ActivationChance: 25.0
  AssignationChance: 100.0
  MinimumRange: 0
  MaximumRange: 16
  VerticalCoef: 2.0
  HorizontalCoef: 3.0
PO3:
  Type: Potion
  Message: "&4{BOSSNAME} Boss used slowness."
  Effect: slow
  Target: other
  ActivationChance: 25.0
  AssignationChance: 100.0
  MinimumRange: 0
  MaximumRange: 16
  Amplifier: 2
  Duration: 3.0
B2:
  Type: Bomb
  Message: "&4{BOSSNAME} Boss planted a bomb."
  ActivationChance: 15.0
  AssignationChance: 100.0
  MinimumRange: 0
  MaximumRange: 16
  Cooldown: 7.5
  Fuse: 80
  ExplosionRadius: 3
LA10:
  Type: LightningAura
  Message: "&4{BOSSNAME} Boss struck his enemies by lightning"
  ActivationChance: 5.0
  AssignationChance: 100.0
  MinimumRange: 0
  MaximumRange: 16
  Cooldown: 10.0
  AttackRadius: 10
  Damage: 2
TP:
  Type: Teleport
  Message: "&4{BOSSNAME} Boss teleported you"
  CenteredOnFoe: true
  ActivationChance: 5.0
  AssignationChance: 100.0
  MinimumRange: 5
  MaximumRange: 25
  Cooldown: 2.0
TP2:
  Type: Teleport
  Message: "&4{BOSSNAME} Boss pulls you closer"
  CenteredOnFoe: false
  ActivationChance: 5.0
  AssignationChance: 100.0
  MinimumRange: 5
  MaximumRange: 25
  Cooldown: 2.0

  
ConfigVersion: 2.0