# DO NOT TOUCH THIS VARIABLE!
version: 1.7.1

AP25:
  Type: ArmorPierce
  Message: "&4Corrupted {BOSSNAME} used Armor Pierce."
  Probability: 10.0
  Value: 25.0
FP2:
  Type: FirePunch
  Message: "&4Corrupted {BOSSNAME} used Fire Punch."
  Probability: 15.0
  Ticks: 2
KB2:
  Type: Knockback
  Message: "&4Corrupted {BOSSNAME} used Knockback."
  Probability: 25.0
  VerticalCoef: 2.0
  HorizontalCoef: 3.0
PO3:
  Type: Potion
  Message: "&4Corrupted {BOSSNAME} used slowness."
  Effect: slow
  Target: other
  Probability: 25.0
  Amplifier: 2
  Duration: 3.0
B2:
  Type: Bomb
  Message: "&4Corrupted {BOSSNAME} planted a bomb."
  DestroyWorld: false
  Fire: true
  Probability: 15.0
  Cooldown: 7.5
  Fuse: 80
  Radius: 3
LA10:
  Type: LightningAura
  Message: "&4Corrupted {BOSSNAME} struck his enemies by lightning"
  Fire: false
  Probability: 5.0
  Cooldown: 10.0
  Radius: 10
  Damage: 2