AP25:
  Type: ArmorPierce
  Message: "&4{BOSSNAME} Boss used Armor Pierce."
  ActivationChance: 10.0
  AssignationChance: 100.0
  Value: 25.0
FP2:
  Type: FirePunch
  Message: "&4{BOSSNAME} Boss used Fire Punch."
  ActivationChance: 15.0
  AssignationChance: 100.0
  Ticks: 2
KB2:
  Type: Knockback
  Message: "&4{BOSSNAME} Boss used Knockback."
  ActivationChance: 25.0
  AssignationChance: 100.0
  VerticalCoef: 2.0
  HorizontalCoef: 3.0
PO3:
  Type: Potion
  Message: "&4{BOSSNAME} Boss used slowness."
  Effect: slow
  Target: other
  ActivationChance: 25.0
  AssignationChance: 100.0
  Amplifier: 2
  Duration: 3.0
B2:
  Type: Bomb
  Message: "&4{BOSSNAME} Boss planted a bomb."
  ActivationChance: 15.0
  AssignationChance: 100.0
  Cooldown: 7.5
  Fuse: 80
  ExplosionRadius: 3
LA10:
  Type: LightningAura
  Message: "&4{BOSSNAME} Boss struck his enemies by lightning"
  ActivationChance: 5.0
  AssignationChance: 100.0
  Cooldown: 10.0
  AttackRadius: 10
  Damage: 2

ConfigVersion: 2.0