Blaze:
  EntityType: Blaze
  Loot:
    FirstRoll:
      FirstItem: 370:0 20.0 1 1
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
CaveSpider:
  EntityType: CaveSpider
  Loot:
    FirstRoll:
      FirstItem: 376:0 20.0 1 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 3.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Creeper:
  EntityType: Creeper
  Loot:
    FirstRoll:
      FirstItem: 46:0 20.0 1 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 3.75
    Damage: 2.0
    Experience: 10.5
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Enderman:
  EntityType: Enderman
  Loot:
    FirstRoll:
      FirstItem: 121:0 20.0 1 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 3.75
    Damage: 2.0
    Experience: 10.5
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Ghast:
  EntityType: Ghast
  Loot:
    FirstRoll:
      FirstItem: 348:0 20.0 4 8
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
LavaSlime:
  EntityType: LavaSlime
  Loot:
    FirstRoll:
      FirstItem: 341:0 20.0 1 3
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
PigZombie:
  EntityType: PigZombie
  Loot:
    FirstRoll:
      FirstItem: 266:0 20.0 1 1
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Silverfish:
  EntityType: SilverFish
  Loot:
    FirstRoll:
      FirstItem: 350:0 20.0 1 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 7.5
    Damage: 4.0
    Experience: 5.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Skeleton:
  EntityType: Skeleton
  Loot:
    FirstRoll:
      FirstItem: 261:0 3.5 1 1
      SecondItem: 262:0 20.0 2 4
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Slime:
  EntityType: Slime
  Loot:
    FirstRoll:
      FirstItem: 378:0 20.0 1 3
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Spider:
  EntityType: Spider
  Loot:
    FirstRoll:
      FirstItem: 35:0 20.0 1 2
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 3.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Witch:
  EntityType: Witch
  Loot:
    FirstRoll:
      FirstItem: 288:0 20.0 1 3
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true
Zombie:
  EntityType: Zombie
  EquipmentSet: diamond
  Loot:
    FirstRoll:
      FirstItem: 288:0 20.0 1 3
  Spawn:
    Probability: 3.0
    SpawnerProbability: 1.0
    MaxSpawnHeight: 256.0
  Stats:
    Health: 5.5
    Damage: 2.0
    Experience: 8.0
  Immunity:
    Fire: true
    Lava: true
    EnvironmentalFireTick: true
    Fall: true
    Contact: true
    Drowning: true
    Suffocation: true


ConfigVersion: 2.0