Command:
  Ignore:
    Delay: 120
  Spawn:
    Max: 50
Message:
  PlayerFoundBoss:
    ToPlayer: '&cYou attacked a Corrupted {BOSSNAME} boss!'
    ToOthers: '&c{PLAYER} found a Corrupted {BOSSNAME}!'
  BossFoundPlayer:
    ToPlayer: '&cA Corrupted {BOSSNAME}!'
    ToOthers: '&cA Corrupted {BOSSNAME} found {PLAYER}!'
  Proximity: '&4You feel an evil presence...'
  ViewerMessage: 'Corrupted {BOSSNAME} Health: {HEALTH} (-{DAMAGE})'
  ViewerDefeated: 'Corrupted {BOSSNAME} has been defeated.'
Task:
  DrawBossEffect: 1.0
  CheckEntityProximity: 0.5
  CheckEntityHealth: 2.0
  CheckEntityExistence: 2.0
  SavePlayerData: 600.0
Boss:
  OverwriteDrops: false
  SetHealthAsMultiplier: true
  SetDamageAsMultiplier: true
  SetExperienceAsMultiplier: true

CheckUpdateOnStartup: true

#Do not touch this variable
ConfigVersion: 2.0