name: Corruption
main: com.mcdr.corruption.Corruption
version: 2.3.3
authors: [Erackron, Pyriphlegethon]
softdepend: [Vault, PermissionsEx, PermissionsBukkit, bPermissions, GroupManager, zPermissions, Permissions, mcMMO, Heroes]
commands:
  corruption:
    aliases: [cor]
    description: Corruption base command
    permission: cor
    usage: Type /<command> help for more information
permissions:
  cor.*:
    description: Give access to all Corruption permissions.
    children:
      cor.clear: true
      cor.help: true
      cor.ignore.*: true
      cor.info: true
      cor.reload: true
      cor.list: true
      cor.loglevel: true
      cor.spawn.*: true
      cor.stats: true
      cor.update: true
      cor.viewer: true
      cor.version: true
    default: op
  cor:
    description: Corruption base command
    default: true
  cor.clear:
    description: Clear informations given by /cor info.
    default: false
  cor.help:
    description: Display command uses.
    default: true
  cor.ignore.*:
    description: Give access to all /cor ignore permissions.
    children:
      cor.ignore: true
      cor.ignore.immediate: true
    default: false
  cor.ignore:
    description: Toggle ignore state, which allows to not be affected by bosses.
    default: false
  cor.ignore.immediate:
    description: Allow to bypass /cor ignore delay
    default: false
  cor.info:
    description: Display some global and non-lasting stats.
    default: false
  cor.reload:
    description: Reload configuration files.
    default: false
  cor.list:
    description: Display the location of active bosses.
    default: false
  cor.loglevel:
    description: Change the LogLevel to control the amount of log messages from this plugin.
    default: false
  cor.spawn.*:
    description: Give access to all /cor spawn and /cor region permissions.
    children:
      cor.spawn: true
      cor.spawn.region.*: true
    default: false
  cor.spawn:
    description: Spawn one or multiple bosses on the targeted block or given location.
    default: false
  cor.spawn.region.*:
    description: Give access to all /cor region permissions.
    children:
      cor.spawn.region.list: true
      cor.spawn.region.info: true
      cor.spawn.region.toggle: true
      cor.spawn.region.edit: true
      cor.spawn.region.manage: true
    default: false
  cor.spawn.region.list:
    description: List existing spawners in a given World or globally without the extra parameter.
    default: false
  cor.spawn.region.info:
    description: Get detailed information about spawners matching the name or id or spawners nearby without the extra parameter.
    default: false
  cor.spawn.region.toggle:
    description: Enable/disable spawners using /cor region <enable|disable> [name|id]
    default: false
  cor.spawn.region.edit:
    description: Edit spawner settings (including spawnable bosses) using /cor region edit
    default: false
  cor.spawn.region.manage:
    description: Add/remove spawners using /cor region <add|remove> [name|id] [options]
    default: false
  cor.stats:
    description: Display the leaderboard, or player stats.
    default: false
  cor.update:
    description: Check for updates and install them if avaicorle.
    default: false
  cor.viewer:
    description: Toggle viewer state, which allows to see boss healths.
    default: false
  cor.version:
    description: Check the version number of the plugin
    default: true