name: Corruption
main: com.mcdr.corruption.Corruption
version: 2.1.2
authors: [Erackron, Pyriphlegethon]
softdepend: [Vault]
commands:
  corruption:
    aliases: [cor]
    description: Corruption base command
    permission: cor
    usage: Type /<command> help for more information
permissions:
  cor.*:
    description: Give access to all Corruption permissions.
    children:
      cor.clear: true
      cor.help: true
      cor.ignore.*: true
      cor.info: true
      cor.reload: true
      cor.list: true
      cor.spawn: true
      cor.stats: true
      cor.update: true
      cor.viewer: true
    default: op
  cor:
    description: Likeaboss base command
    default: true
  cor.clear:
    description: Clear informations given by /cor info.
    default: false
  cor.help:
    description: Display command uses.
    default: true
  cor.ignore.*:
    description: Give access to all /cor ignore permissions.
    children:
      cor.ignore: true
      cor.ignore.immediate: true
    default: false
  cor.ignore:
    description: Toggle ignore state, which allows to not be affected by bosses.
    default: false
  cor.ignore.immediate:
    description: Allow to bypass /cor ignore delay
    default: false
  cor.info:
    description: Display some global and non-lasting stats.
    default: false
  cor.reload:
    description: Reload configuration files.
    default: false
  cor.list:
    description: Display the location of active bosses.
    default: false
  cor.spawn:
    description: Spawn one or multiple bosses on the targeted block.
    default: false
  cor.stats:
    description: Display the leaderboard, or player stats.
    default: false
  cor.update:
    description: Check for updates and install them if avaicorle.
    default: false
  cor.viewer:
    description: Toggle viewer state, which allows to see boss healths.
    default: false